services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - TZ=Europe/Paris
      - AUTO_UPDATE=true #optional
    volumes:
      - ./jackett:/config
      - ${MEDIA_DIR}/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - TZ=Europe/Paris
    ports:
      - 8191:8191
    restart: unless-stopped

  transmission:
    container_name: transmission
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - ./protonvpn/:/etc/openvpn/custom/
      - ./transmission:/config # where transmission-home is stored
      - ${MEDIA_DIR}/transmission/downloads:/downloads # where transmission will store the data
    environment:
      - OPENVPN_PROVIDER=custom
      - OPENVPN_CONFIG=${PROTONVPN_NODE}.protonvpn.udp
      - OPENVPN_USERNAME=${PROTONVPN_USERNAME}+pmp
      - OPENVPN_PASSWORD=${PROTONVPN_PASSWORD}
      - LOCAL_NETWORK=192.168.1.0/24
      - TZ=Europe/Paris
    logging:
      driver: json-file
      options:
        max-size: 10m
    dns:
      - 1.1.1.1
      - 1.1.0.0
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    image: haugene/transmission-openvpn
